version: "3.9"
services:
  rabbitmq_orders:
    restart: always
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_NODENAME: orders-rabbitmq-node
    volumes:
      - ./development/rabbitmq/data/orders/:/var/lib/rabbitmq/
  postgres_orders:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 1q2w3e!
    volumes:
      - ./development/postgres/data/orders:/var/lib/postgresql/data
      - ./development/postgres/init/orders:/docker-entrypoint-initdb.d/